version: '2.1'

services:
  postgres:
    image: postgres:9.6-alpine
    ports:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=touchdown1!

  yopa:
    image: pagarme/yopa:latest
    command: java -Xms64m -Xmx256m -jar uberjar.jar -c /tmp/yopa-in/config.yml -o /tmp/dev-env-aws-regions-override.xml
    ports:
      - 47195
    volumes:
      - ./yopa-config.yml:/tmp/yopa-in/config.yml:ro
    healthcheck:
      test: [
        "CMD-SHELL",
        "curl -f 'http://localhost:47195?Action=GetQueueUrl&QueueName=test'",
        "&&",
        "curl -f 'http://localhost:47195?Action=GetQueueUrl&QueueName=boletos-to-register'",
      ]
      interval: 20s
      retries: 10

  test-dependencies:
    image: busybox
    depends_on:
      postgres:
        condition: service_started
      yopa:
        condition: service_healthy
      superbowleto-web:
        condition: service_started

  test:
    build: .
    command: npm test
    environment:
      - API_ENV=test
    volumes:
      - .:/home/quarterback/superbowleto
      - /home/quarterback/superbowleto/node_modules
    depends_on:
      - test-dependencies
    user: '0'

  superbowleto-web:
    build: .
    command: node src/bin/server.js
    ports:
      - "3000:3000"
    environment:
      - API_ENV=test
      - PORT=3000
    depends_on:
      - postgres
      - yopa
    links:
      - postgres
      - yopa

  superbowleto-worker:
    build: .
    command: node src/bin/worker.js
    environment:
      - API_ENV=test
    volumes:
      - .:/superbowleto
      - /superbowleto/node_modules
    depends_on:
      - postgres
      - yopa
    links:
      - postgres
      - yopa
